version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=drones4all
      - MYSQL_ROOT_PASSWORD=TM1q2w3e.
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - 3304
    ports:
      - 3304:3304

  php:
    image: soulless32/prueba:php54-1
    volumes:
      - ./code/:/var/www/html
    expose:
      - 880
    ports:
      - 880:880
    links:
      - mysql

